### ISSUE TITLE
Log of errors during installation

### ISSUE THREAD

**Issue by MridulS** [Murali-group/GraphSpace#187]
@adbharadwaj is currently working on updating the settings and requirements file in the branch https://github.com/Murali-group/GraphSpace/commits/%23176 .
I just wanted to keep a log of errors if one installs the graphspace repo on a clean ubuntu 14.04 machine using the instructions on README page.

```
    import bcrypt
ImportError: No module named bcrypt
Traceback (most recent call last):
  File "local_settings.py", line 146, in <module>
    migrate()
  File "local_settings.py", line 102, in migrate
    subprocess.check_output([sys.executable, "manage.py", "migrate"])
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/python', 'manage.py', 'migrate']' returned non-zero exit status 1
```

Solution to error:

```
pip install bcrypt
```

Reason for error:
https://github.com/Murali-group/GraphSpace/blob/master/local_settings.py#L130
 bcrypt missing from required packages

```
    required_packages = ["django", "py-bcrypt","sqlalchemy","django-analytical","poster","networkx", "Sphinx"]

```

Next error:

```
Installing collected packages: py-bcrypt
  Running setup.py install for py-bcrypt ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7vxS7z/py-bcrypt/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-RKrlNX-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/bcrypt
    copying bcrypt/__init__.py -> build/lib.linux-x86_64-2.7/bcrypt
    running build_ext
    building 'bcrypt._bcrypt' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/bcrypt
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c bcrypt/bcrypt.c -o build/temp.linux-x86_64-2.7/bcrypt/bcrypt.o
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7vxS7z/py-bcrypt/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-RKrlNX-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-7vxS7z/py-bcrypt/
```

solution to the error:

```
sudo apt-get install python-dev
```

Reason: This is not really a graphspace issue, but python-dev should be installed for py-bcrypt.

Next error:

```
mridul@ubuntu-512mb-blr1-01:~/GraphSpace$ chmod 777 graphspace.db
chmod: changing permissions of ‘graphspace.db’: Operation not permitted
```

This one is weird because last time i didn't need sudo permission to run `chmod`

Solution: add sudo to it

executing the command `python manage.py runserver` doesn't throw any error.
Next error:  if I try to create a new user through the browser

```
Internal Server Error: /register/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mridul/GraphSpace/graphs/views.py", line 1280, in register
    bcrypt.gensalt())
  File "/usr/local/lib/python2.7/dist-packages/bcrypt/__init__.py", line 50, in gensalt
    output = _bcrypt.ffi.new("unsigned char[]", 30)
AttributeError: 'module' object has no attribute 'ffi'
```

Solution: Still looking for it.

NOTE: This is without using virtualenvs.

**Comment by MridulS** [comment]
NOTE: all these tests including above are ran using non-root accounts.
NOTE: This installation is done on a fresh ubuntu 14.04 machine.
NOTE: Using virtualenv as for installation rather than `sudo pip`

after executing `python local_settings.py`
Error:
```
Traceback (most recent call last):
  File "local_settings.py", line 138, in <module>
    import django
ImportError: No module named django
```
Solution: run `pip install django`
Reason: not sure about this, but it can be problematic if you install with `sudo` inside a `virtualenv` which the file `local_settings.py` does.
https://github.com/Murali-group/GraphSpace/blob/master/local_settings.py#L110

Next error:
```
ImportError: No module named analytical
Traceback (most recent call last):
  File "local_settings.py", line 146, in <module>
    migrate()
  File "local_settings.py", line 102, in migrate
    subprocess.check_output([sys.executable, "manage.py", "migrate"])
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/home/mridul/venv/graphspace/bin/python', 'manage.py', 'migrate']' returned non-zero exit status 1
```

Solution: `pip install django-analytical`

As you can guess this will happen for all the packages.
But the problem with this approach is that the current local_settings.py file doesn't test all the requirements. I only had to run the following commands to get `python local_settings.py` working.
```
pip install django
python local_settings.py
pip install django-analytical
pip install sqlalchemy
pip install bcrypt
pip install requests
```
packages like networkx, poster, Sphinx are listed as requirements but they are not installed in the virtual environment by the local_settings.py file.

```
>>> import networkx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named networkx
```
The command `python local_settings.py should throw an error in this case.

in this case `chmod 777 graphspace.db` runs without `sudo` and `python manage.py runserver` also executes without any issues.

But if I try to create a new user through the browser a different error is thrown.
 
```
Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/mridul/venv/graphspace/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mridul/venv/graphspace/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mridul/GraphSpace/graphs/views.py", line 1280, in register
    bcrypt.gensalt())
  File "/home/mridul/venv/graphspace/local/lib/python2.7/site-packages/bcrypt/__init__.py", line 61, in hashpw
    raise TypeError("Unicode-objects must be encoded before hashing")
TypeError: Unicode-objects must be encoded before hashing
[17/Jul/2016 16:31:45] "POST /register/ HTTP/1.1" 500 14202
```
Solution: looking for it

NOTE: installed python-dev initially hence no error like previous post.

**Comment by adbharadwaj** [comment]
The installation procedure has been streamlined in GraphSpace 2.0. Please refer to README.md for instructions on how to install GraphSpace.
