### ISSUE TITLE
Improve documentation for "Running GraphSpace locally"

### ISSUE THREAD

**Issue by melvin15may** [Murali-group/GraphSpace#267]
I get the following error on Step 6: Finally, start the GraphSpace server: `python manage.py runserver --settings=graphspace.settings.local`
> Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/melvin/Documents/GSoC/doc_graph/GraphSpace/venv/local/lib/python2.7/site-packages/Django-1.9.7-py2.7.egg/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/melvin/Documents/GSoC/doc_graph/GraphSpace/venv/local/lib/python2.7/site-packages/Django-1.9.7-py2.7.egg/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/melvin/Documents/GSoC/doc_graph/GraphSpace/venv/local/lib/python2.7/site-packages/Django-1.9.7-py2.7.egg/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/melvin/Documents/GSoC/doc_graph/GraphSpace/venv/local/lib/python2.7/site-packages/Django-1.9.7-py2.7.egg/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/melvin/Documents/GSoC/doc_graph/GraphSpace/venv/local/lib/python2.7/site-packages/Django-1.9.7-py2.7.egg/django/core/management/commands/migrate.py", line 89, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/melvin/Documents/GSoC/doc_graph/GraphSpace/venv/local/lib/python2.7/site-packages/Django-1.9.7-py2.7.egg/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/melvin/Documents/GSoC/doc_graph/GraphSpace/venv/local/lib/python2.7/site-packages/Django-1.9.7-py2.7.egg/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/melvin/Documents/GSoC/doc_graph/GraphSpace/venv/local/lib/python2.7/site-packages/Django-1.9.7-py2.7.egg/django/db/migrations/loader.py", line 176, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/melvin/Documents/GSoC/doc_graph/GraphSpace/venv/local/lib/python2.7/site-packages/Django-1.9.7-py2.7.egg/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/home/melvin/Documents/GSoC/doc_graph/GraphSpace/venv/local/lib/python2.7/site-packages/Django-1.9.7-py2.7.egg/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/home/melvin/Documents/GSoC/doc_graph/GraphSpace/venv/local/lib/python2.7/site-packages/Django-1.9.7-py2.7.egg/django/db/backends/base/base.py", line 231, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/home/melvin/Documents/GSoC/doc_graph/GraphSpace/venv/local/lib/python2.7/site-packages/Django-1.9.7-py2.7.egg/django/db/backends/base/base.py", line 204, in _cursor
    self.ensure_connection()
  File "/home/melvin/Documents/GSoC/doc_graph/GraphSpace/venv/local/lib/python2.7/site-packages/Django-1.9.7-py2.7.egg/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/home/melvin/Documents/GSoC/doc_graph/GraphSpace/venv/local/lib/python2.7/site-packages/Django-1.9.7-py2.7.egg/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/melvin/Documents/GSoC/doc_graph/GraphSpace/venv/local/lib/python2.7/site-packages/Django-1.9.7-py2.7.egg/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/home/melvin/Documents/GSoC/doc_graph/GraphSpace/venv/local/lib/python2.7/site-packages/Django-1.9.7-py2.7.egg/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/melvin/Documents/GSoC/doc_graph/GraphSpace/venv/local/lib/python2.7/site-packages/Django-1.9.7-py2.7.egg/django/db/backends/postgresql/base.py", line 175, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/melvin/Documents/GSoC/doc_graph/GraphSpace/venv/lib/python2.7/site-packages/psycopg2-2.6.2-py2.7-linux-x86_64.egg/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: fe_sendauth: no password supplied

This error is related to connection with postgres. I have to create new role in postgres and update the information in `/graphspace/settings/local.py` 

This information should be mentioned in the procedure for running GraphSpace locally.

**Comment by antonwats** [comment]
Having a similar issue:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the foll.
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/yurelw/Coding/summer_project/GraphSpace/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/yurelw/Coding/summer_project/GraphSpace/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/yurelw/Coding/summer_project/GraphSpace/venv/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/yurelw/Coding/summer_project/GraphSpace/venv/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/yurelw/Coding/summer_project/GraphSpace/venv/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/yurelw/Coding/summer_project/GraphSpace/venv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/yurelw/Coding/summer_project/GraphSpace/venv/lib/python2.7/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/home/yurelw/Coding/summer_project/GraphSpace/venv/lib/python2.7/site-packages/django/db/migrations/loader.py", line 209, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/yurelw/Coding/summer_project/GraphSpace/venv/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/home/yurelw/Coding/summer_project/GraphSpace/venv/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/home/yurelw/Coding/summer_project/GraphSpace/venv/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/home/yurelw/Coding/summer_project/GraphSpace/venv/lib/python2.7/site-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/home/yurelw/Coding/summer_project/GraphSpace/venv/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/home/yurelw/Coding/summer_project/GraphSpace/venv/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/yurelw/Coding/summer_project/GraphSpace/venv/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/home/yurelw/Coding/summer_project/GraphSpace/venv/lib/python2.7/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/yurelw/Coding/summer_project/GraphSpace/venv/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/yurelw/Coding/summer_project/GraphSpace/venv/lib/python2.7/site-packages/psycopg2-2.6.2-py2.7-linux-x86_64.egg/psycopg2/__init__.py", line 164, in t
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: FATAL:  Ident authentication failed for user "yurelw"

**Comment by melvin15may** [comment]
@antonwats Double check the postgres username and password.

**Comment by antonwats** [comment]
Ah thank you, do you know where would I go to find where that is or what it is set to?

**Comment by melvin15may** [comment]
You can update the credentials in the `/graphspace/settings/local.py` file. Look for `DATABASES` variable.

**Comment by antonwats** [comment]
Okay, I actually messed around with this file earlier, though I'm not completely sure what it should be set to. First the username was 'adb' but I set it to my own thinking that it would then work with my own postgres installation, but that doesn't seem to be the case. Should I be editing my postgres installation instead?

**Comment by melvin15may** [comment]
You can follow the steps given [here](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-postgresql-on-ubuntu-16-04) and create a new role and give permission to that role to access the database (one you use with graphspace).
