### ISSUE TITLE
Unable to run GraphSpace locally

### ISSUE THREAD

**Issue by lohani2280** [Murali-group/GraphSpace#337]
```
Using /home/lohani/open-source/GraphSpace_Venv/lib/python2.7/site-packages
Finished processing dependencies for GraphSpace-Server==1.2.0
System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DEBUG.
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/lohani/open-source/GraphSpace_Venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/lohani/open-source/GraphSpace_Venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/lohani/open-source/GraphSpace_Venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/lohani/open-source/GraphSpace_Venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/lohani/open-source/GraphSpace_Venv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 89, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/lohani/open-source/GraphSpace_Venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/lohani/open-source/GraphSpace_Venv/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/lohani/open-source/GraphSpace_Venv/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 176, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/lohani/open-source/GraphSpace_Venv/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/home/lohani/open-source/GraphSpace_Venv/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/home/lohani/open-source/GraphSpace_Venv/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/home/lohani/open-source/GraphSpace_Venv/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 204, in _cursor
    self.ensure_connection()
  File "/home/lohani/open-source/GraphSpace_Venv/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/home/lohani/open-source/GraphSpace_Venv/local/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/lohani/open-source/GraphSpace_Venv/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/home/lohani/open-source/GraphSpace_Venv/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/lohani/open-source/GraphSpace_Venv/local/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 175, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/lohani/open-source/GraphSpace_Venv/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "lohani"
FATAL:  password authentication failed for user "lohani"

install.sh: 5: install.sh: bower: not found
```
I am new to GraphSpace. I tried installing GraphSpace locally and got stuck here.Please help.

**Comment by lohani2280** [comment]
Sorry, I have resolve the above `password authentication` failure. However, still when i run                  `sh install.sh`
i  get following error:
```
Using /home/lohani/open-source/GraphSpace_Venv/lib/python2.7/site-packages
Finished processing dependencies for GraphSpace-Server==1.2.0
System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DEBUG.
Operations to perform:
  Apply all migrations: admin, contenttypes, auth, sessions
Running migrations:
  No migrations to apply.
install.sh: 5: install.sh: bower: not found

```

**Comment by lohani2280** [comment]
I have gone through the issue https://github.com/Murali-group/GraphSpace/issues/333 and it helped me to resolve my issue. However, when i start my development server at http://127.0.0.1:8000/ , the UI is quiet inconsistent. Here is the image-
![screenshot from 2018-01-24 15-58-09](https://user-images.githubusercontent.com/18470647/35327866-b8696cde-0120-11e8-9c1c-45f98f026630.png)

Also when i login using `Username: user1@example.com Password: user1`, I am getting this-
![screenshot from 2018-01-24 16-09-48](https://user-images.githubusercontent.com/18470647/35327967-f50a85a6-0120-11e8-9a31-ad964be889af.png)

**Comment by lohani2280** [comment]
I have installed the GraphSpace. However, when I try to upload graph by filling the graph name and a .cyjs network file and then when i click the submit button, i get following error-

![screenshot from 2018-01-27 12-05-28](https://user-images.githubusercontent.com/18470647/35469424-58d2478c-035a-11e8-9571-e8893d200404.png)


![screenshot from 2018-01-27 12-05-34](https://user-images.githubusercontent.com/18470647/35469425-5d7eb6bc-035a-11e8-9bd8-3c637174ce25.png)

**Comment by melvin15may** [comment]
`CSRF verification failed` is a common error with Django. Follow [this](https://stackoverflow.com/questions/9692625/csrf-verification-failed-request-aborted-on-django) stackoverflow answer.

**Comment by lohani2280** [comment]
@melvin15may Thanks for your help. I have solved the upload graph issue. The problem was basically with my elasticsearch configuration. I am still getting facing problems with UI working. I have configured the proxy for bower but still the issue is not getting resolved for the UI. 
![screenshot from 2018-01-29 03-02-56](https://user-images.githubusercontent.com/18470647/35487378-e1b63ae4-04a0-11e8-8a47-3f49730635e0.png)

**Comment by melvin15may** [comment]
@lohani2280 Not sure why its not working. These files are not able to find `Popper.js` and probably the first 2 errors are also something similar.

**Comment by adbharadwaj** [comment]
@lohani2280 Did bower install run successfully ?? I would recommend deleting the `bower_components` folder and reinstalling the dependencies. This time using `sudo bower install`.

**Comment by adbharadwaj** [comment]
@lohani2280 found the solution. Run the following command to fix the issue. 

```sh
bower install bootstrap#3.3.7
```
The problem was that bootstrap dependency was missing from bower.json file and `bower install bootstrap` command installs bootstrap V4 which doesn't come with plugins like popover.js by default anymore. 

I am fixing this issue by adding bootstrap dependency with proper version number.

**Comment by adbharadwaj** [comment]
@lohani2280 please close the issue if problem is resolved.

**Comment by lohani2280** [comment]
@adbharadwaj Thank You so much for the help. Yes, now the problem is resolved. I am closing this  issue.
